id: P003251
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W3CN2376
  title: ས་བདག་བཤགས་འབུམ།
  author: ''
  volumes:
    99c685b91a1a4e008fa2707778bd46ff:
      image_group_id: I3CN2378
      title: ''
      volume_number: 1
      total_pages: 37
      base_file: v001.txt
